// <auto-generated />
using System;
using InmobiliariaAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InmobiliariaAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InmobiliariaDbContext))]
    [Migration("20251110021046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("fechaFinalizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_finalizacion");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("id_inmueble")
                        .HasColumnType("int")
                        .HasColumnName("id_inmueble");

                    b.Property<int>("id_inquilino")
                        .HasColumnType("int")
                        .HasColumnName("id_inquilino");

                    b.Property<decimal>("montoAlquiler")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_alquiler");

                    b.HasKey("id");

                    b.HasIndex("id_inmueble");

                    b.HasIndex("id_inquilino");

                    b.ToTable("contratos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.ImagenInmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("id_inmueble")
                        .HasColumnType("int")
                        .HasColumnName("id_inmueble");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("url");

                    b.HasKey("id");

                    b.HasIndex("id_inmueble");

                    b.ToTable("imagenes_inmuebles");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ambientes")
                        .HasColumnType("int")
                        .HasColumnName("ambientes");

                    b.Property<string>("direccion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("direccion");

                    b.Property<bool>("disponible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disponible");

                    b.Property<int>("id_propietario")
                        .HasColumnType("int")
                        .HasColumnName("id_propietario");

                    b.Property<int>("id_tipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<int>("id_uso")
                        .HasColumnType("int")
                        .HasColumnName("id_uso");

                    b.Property<decimal>("latitud")
                        .HasColumnType("decimal(10,8)")
                        .HasColumnName("latitud");

                    b.Property<decimal>("longitud")
                        .HasColumnType("decimal(11,8)")
                        .HasColumnName("longitud");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<int>("superficie")
                        .HasColumnType("int")
                        .HasColumnName("superficie");

                    b.HasKey("id");

                    b.HasIndex("id_propietario");

                    b.HasIndex("id_tipo");

                    b.HasIndex("id_uso");

                    b.ToTable("inmuebles");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inquilino", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<int>("dni")
                        .HasColumnType("int")
                        .HasColumnName("dni");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("id");

                    b.HasIndex("dni")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("inquilinos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("detalle");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("fechaPago")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_pago");

                    b.Property<int>("id_contrato")
                        .HasColumnType("int")
                        .HasColumnName("id_contrato");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("id");

                    b.HasIndex("id_contrato");

                    b.ToTable("pagos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Propietario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<int>("dni")
                        .HasColumnType("int")
                        .HasColumnName("dni");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("password")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("id");

                    b.HasIndex("dni")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("propietarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            activo = true,
                            apellido = "Gómez",
                            dni = 20123456,
                            email = "carlos.gomez@example.com",
                            nombre = "Carlos",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000001"
                        },
                        new
                        {
                            id = 2,
                            activo = true,
                            apellido = "Fernández",
                            dni = 20987654,
                            email = "maria.fernandez@example.com",
                            nombre = "María",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000002"
                        },
                        new
                        {
                            id = 3,
                            activo = true,
                            apellido = "Pérez",
                            dni = 19543210,
                            email = "lucia.perez@example.com",
                            nombre = "Lucía",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000003"
                        },
                        new
                        {
                            id = 4,
                            activo = true,
                            apellido = "Rodríguez",
                            dni = 21456789,
                            email = "javier.rodriguez@example.com",
                            nombre = "Javier",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000004"
                        },
                        new
                        {
                            id = 5,
                            activo = true,
                            apellido = "Lopez",
                            dni = 22345678,
                            email = "ana.lopez@example.com",
                            nombre = "Ana",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000005"
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.TipoInmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("tipos_inmueble");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.UsoInmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("usos_inmueble");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Inmueble", "Inmueble")
                        .WithMany("Contratos")
                        .HasForeignKey("id_inmueble")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InmobiliariaAPI.Domain.Entities.Inquilino", "Inquilino")
                        .WithMany("Contratos")
                        .HasForeignKey("id_inquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.ImagenInmueble", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Inmueble", "Inmueble")
                        .WithMany("Imagenes")
                        .HasForeignKey("id_inmueble")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inmueble", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Propietario", "Propietario")
                        .WithMany("Inmuebles")
                        .HasForeignKey("id_propietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InmobiliariaAPI.Domain.Entities.TipoInmueble", "Tipo")
                        .WithMany("Inmuebles")
                        .HasForeignKey("id_tipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InmobiliariaAPI.Domain.Entities.UsoInmueble", "Uso")
                        .WithMany("Inmuebles")
                        .HasForeignKey("id_uso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propietario");

                    b.Navigation("Tipo");

                    b.Navigation("Uso");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Pago", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Pagos")
                        .HasForeignKey("id_contrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inmueble", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inquilino", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Propietario", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.TipoInmueble", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.UsoInmueble", b =>
                {
                    b.Navigation("Inmuebles");
                });
#pragma warning restore 612, 618
        }
    }
}
