// <auto-generated />
using System;
using InmobiliariaAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InmobiliariaAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InmobiliariaDbContext))]
    [Migration("20251110063247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("fechaFinalizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_finalizacion");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("inmueble_id")
                        .HasColumnType("int")
                        .HasColumnName("inmueble_id");

                    b.Property<int>("inquilino_id")
                        .HasColumnType("int")
                        .HasColumnName("inquilino_id");

                    b.Property<decimal>("montoAlquiler")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_alquiler");

                    b.HasKey("id");

                    b.HasIndex("inmueble_id");

                    b.HasIndex("inquilino_id");

                    b.ToTable("contratos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.ImagenInmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("inmueble_id")
                        .HasColumnType("int")
                        .HasColumnName("inmueble_id");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("url");

                    b.HasKey("id");

                    b.HasIndex("inmueble_id")
                        .IsUnique();

                    b.ToTable("imagenes_inmuebles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            inmueble_id = 1,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 2,
                            inmueble_id = 2,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 3,
                            inmueble_id = 3,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 4,
                            inmueble_id = 4,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 5,
                            inmueble_id = 5,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 6,
                            inmueble_id = 6,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 7,
                            inmueble_id = 7,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 8,
                            inmueble_id = 8,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 9,
                            inmueble_id = 9,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 10,
                            inmueble_id = 10,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 11,
                            inmueble_id = 11,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 12,
                            inmueble_id = 12,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 13,
                            inmueble_id = 13,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 14,
                            inmueble_id = 14,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 15,
                            inmueble_id = 15,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 16,
                            inmueble_id = 16,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 17,
                            inmueble_id = 17,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 18,
                            inmueble_id = 18,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 19,
                            inmueble_id = 19,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 20,
                            inmueble_id = 20,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 21,
                            inmueble_id = 21,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 22,
                            inmueble_id = 22,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 23,
                            inmueble_id = 23,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 24,
                            inmueble_id = 24,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 25,
                            inmueble_id = 25,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ambientes")
                        .HasColumnType("int")
                        .HasColumnName("ambientes");

                    b.Property<string>("direccion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("direccion");

                    b.Property<bool>("disponible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disponible");

                    b.Property<string>("latitud")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("latitud");

                    b.Property<string>("longitud")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("longitud");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<int>("propietario_id")
                        .HasColumnType("int")
                        .HasColumnName("propietario_id");

                    b.Property<int>("superficie")
                        .HasColumnType("int")
                        .HasColumnName("superficie");

                    b.Property<int>("tipo_id")
                        .HasColumnType("int")
                        .HasColumnName("tipo_id");

                    b.Property<int>("uso_id")
                        .HasColumnType("int")
                        .HasColumnName("uso_id");

                    b.HasKey("id");

                    b.HasIndex("propietario_id");

                    b.HasIndex("tipo_id");

                    b.HasIndex("uso_id");

                    b.ToTable("inmuebles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            ambientes = 4,
                            direccion = "Av. España 102",
                            disponible = true,
                            latitud = "-33.296512",
                            longitud = "-66.335421",
                            precio = 120000m,
                            propietario_id = 1,
                            superficie = 140,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 2,
                            ambientes = 3,
                            direccion = "Belgrano 450",
                            disponible = true,
                            latitud = "-33.297845",
                            longitud = "-66.333210",
                            precio = 98000m,
                            propietario_id = 1,
                            superficie = 95,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 3,
                            ambientes = 2,
                            direccion = "Junín 780",
                            disponible = false,
                            latitud = "-33.298762",
                            longitud = "-66.331567",
                            precio = 75000m,
                            propietario_id = 1,
                            superficie = 70,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 4,
                            ambientes = 5,
                            direccion = "Mitre 1200",
                            disponible = true,
                            latitud = "-33.299843",
                            longitud = "-66.336789",
                            precio = 145000m,
                            propietario_id = 1,
                            superficie = 180,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 5,
                            ambientes = 3,
                            direccion = "Colón 350",
                            disponible = false,
                            latitud = "-33.301256",
                            longitud = "-66.334123",
                            precio = 210000m,
                            propietario_id = 1,
                            superficie = 110,
                            tipo_id = 3,
                            uso_id = 2
                        },
                        new
                        {
                            id = 6,
                            ambientes = 4,
                            direccion = "Buenos Aires 89",
                            disponible = true,
                            latitud = "-33.305612",
                            longitud = "-66.337456",
                            precio = 152000m,
                            propietario_id = 2,
                            superficie = 160,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 7,
                            ambientes = 3,
                            direccion = "Chacabuco 560",
                            disponible = true,
                            latitud = "-33.304123",
                            longitud = "-66.332345",
                            precio = 99000m,
                            propietario_id = 2,
                            superficie = 100,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 8,
                            ambientes = 2,
                            direccion = "San Martín 910",
                            disponible = false,
                            latitud = "-33.302981",
                            longitud = "-66.329876",
                            precio = 82000m,
                            propietario_id = 2,
                            superficie = 75,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 9,
                            ambientes = 5,
                            direccion = "Rivadavia 2100",
                            disponible = false,
                            latitud = "-33.306745",
                            longitud = "-66.340012",
                            precio = 165000m,
                            propietario_id = 2,
                            superficie = 200,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 10,
                            ambientes = 4,
                            direccion = "Pringles 45",
                            disponible = true,
                            latitud = "-33.303567",
                            longitud = "-66.327543",
                            precio = 230000m,
                            propietario_id = 2,
                            superficie = 150,
                            tipo_id = 3,
                            uso_id = 2
                        },
                        new
                        {
                            id = 11,
                            ambientes = 3,
                            direccion = "Pueyrredón 320",
                            disponible = true,
                            latitud = "-33.312345",
                            longitud = "-66.341234",
                            precio = 138000m,
                            propietario_id = 3,
                            superficie = 120,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 12,
                            ambientes = 2,
                            direccion = "Ituzaingó 654",
                            disponible = true,
                            latitud = "-33.310234",
                            longitud = "-66.338765",
                            precio = 87000m,
                            propietario_id = 3,
                            superficie = 68,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 13,
                            ambientes = 4,
                            direccion = "Catamarca 870",
                            disponible = false,
                            latitud = "-33.311789",
                            longitud = "-66.336543",
                            precio = 149000m,
                            propietario_id = 3,
                            superficie = 140,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 14,
                            ambientes = 1,
                            direccion = "Lafinur 120",
                            disponible = true,
                            latitud = "-33.309432",
                            longitud = "-66.333210",
                            precio = 110000m,
                            propietario_id = 3,
                            superficie = 55,
                            tipo_id = 4,
                            uso_id = 2
                        },
                        new
                        {
                            id = 15,
                            ambientes = 3,
                            direccion = "Ayacucho 410",
                            disponible = false,
                            latitud = "-33.308765",
                            longitud = "-66.331098",
                            precio = 96000m,
                            propietario_id = 3,
                            superficie = 105,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 16,
                            ambientes = 4,
                            direccion = "Independencia 1500",
                            disponible = true,
                            latitud = "-33.318765",
                            longitud = "-66.346543",
                            precio = 155000m,
                            propietario_id = 4,
                            superficie = 150,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 17,
                            ambientes = 3,
                            direccion = "Balcarce 620",
                            disponible = true,
                            latitud = "-33.316234",
                            longitud = "-66.342101",
                            precio = 93000m,
                            propietario_id = 4,
                            superficie = 98,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 18,
                            ambientes = 2,
                            direccion = "Los Puquios 45",
                            disponible = false,
                            latitud = "-33.320987",
                            longitud = "-66.347890",
                            precio = 78000m,
                            propietario_id = 4,
                            superficie = 65,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 19,
                            ambientes = 5,
                            direccion = "Illia 3450",
                            disponible = false,
                            latitud = "-33.317654",
                            longitud = "-66.349321",
                            precio = 172000m,
                            propietario_id = 4,
                            superficie = 210,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 20,
                            ambientes = 4,
                            direccion = "Ruta 3 Km 5",
                            disponible = true,
                            latitud = "-33.322345",
                            longitud = "-66.351234",
                            precio = 240000m,
                            propietario_id = 4,
                            superficie = 190,
                            tipo_id = 3,
                            uso_id = 2
                        },
                        new
                        {
                            id = 21,
                            ambientes = 3,
                            direccion = "Esteban Adaro 890",
                            disponible = true,
                            latitud = "-33.325678",
                            longitud = "-66.353456",
                            precio = 142000m,
                            propietario_id = 5,
                            superficie = 115,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 22,
                            ambientes = 2,
                            direccion = "Concarán 120",
                            disponible = true,
                            latitud = "-33.324321",
                            longitud = "-66.356789",
                            precio = 88000m,
                            propietario_id = 5,
                            superficie = 82,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 23,
                            ambientes = 1,
                            direccion = "Fraga 630",
                            disponible = false,
                            latitud = "-33.326543",
                            longitud = "-66.358901",
                            precio = 105000m,
                            propietario_id = 5,
                            superficie = 50,
                            tipo_id = 4,
                            uso_id = 2
                        },
                        new
                        {
                            id = 24,
                            ambientes = 4,
                            direccion = "El Trapiche 270",
                            disponible = true,
                            latitud = "-33.327890",
                            longitud = "-66.360123",
                            precio = 158000m,
                            propietario_id = 5,
                            superficie = 160,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 25,
                            ambientes = 3,
                            direccion = "Potrero de los Funes 410",
                            disponible = false,
                            latitud = "-33.329012",
                            longitud = "-66.362345",
                            precio = 215000m,
                            propietario_id = 5,
                            superficie = 130,
                            tipo_id = 3,
                            uso_id = 2
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inquilino", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("dni")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("dni");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("id");

                    b.HasIndex("dni")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("inquilinos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("contrato_id")
                        .HasColumnType("int")
                        .HasColumnName("contrato_id");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("detalle");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("fechaPago")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("id");

                    b.HasIndex("contrato_id");

                    b.ToTable("pagos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Propietario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("dni");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("id");

                    b.HasIndex("dni")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("propietarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            activo = true,
                            apellido = "Gómez",
                            dni = "20123456",
                            email = "carlos.gomez@example.com",
                            nombre = "Carlos",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000001"
                        },
                        new
                        {
                            id = 2,
                            activo = true,
                            apellido = "Fernández",
                            dni = "20987654",
                            email = "maria.fernandez@example.com",
                            nombre = "María",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000002"
                        },
                        new
                        {
                            id = 3,
                            activo = true,
                            apellido = "Pérez",
                            dni = "19543210",
                            email = "lucia.perez@example.com",
                            nombre = "Lucía",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000003"
                        },
                        new
                        {
                            id = 4,
                            activo = true,
                            apellido = "Rodríguez",
                            dni = "21456789",
                            email = "javier.rodriguez@example.com",
                            nombre = "Javier",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000004"
                        },
                        new
                        {
                            id = 5,
                            activo = true,
                            apellido = "Lopez",
                            dni = "22345678",
                            email = "ana.lopez@example.com",
                            nombre = "Ana",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000005"
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.TipoInmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("tipos_inmueble");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Casa"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Departamento"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Local Comercial"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Oficina"
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.UsoInmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("usos_inmueble");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Residencial"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Comercial"
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Inmueble", "Inmueble")
                        .WithMany("Contratos")
                        .HasForeignKey("inmueble_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InmobiliariaAPI.Domain.Entities.Inquilino", "Inquilino")
                        .WithMany("Contratos")
                        .HasForeignKey("inquilino_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.ImagenInmueble", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Inmueble", "Inmueble")
                        .WithOne("Imagen")
                        .HasForeignKey("InmobiliariaAPI.Domain.Entities.ImagenInmueble", "inmueble_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inmueble", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Propietario", "Propietario")
                        .WithMany("Inmuebles")
                        .HasForeignKey("propietario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InmobiliariaAPI.Domain.Entities.TipoInmueble", "Tipo")
                        .WithMany("Inmuebles")
                        .HasForeignKey("tipo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InmobiliariaAPI.Domain.Entities.UsoInmueble", "Uso")
                        .WithMany("Inmuebles")
                        .HasForeignKey("uso_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propietario");

                    b.Navigation("Tipo");

                    b.Navigation("Uso");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Pago", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Pagos")
                        .HasForeignKey("contrato_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inmueble", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inquilino", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Propietario", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.TipoInmueble", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.UsoInmueble", b =>
                {
                    b.Navigation("Inmuebles");
                });
#pragma warning restore 612, 618
        }
    }
}
