// <auto-generated />
using System;
using InmobiliariaAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InmobiliariaAPI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InmobiliariaDbContext))]
    partial class InmobiliariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("fechaFinalizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_finalizacion");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("inmueble_id")
                        .HasColumnType("int")
                        .HasColumnName("inmueble_id");

                    b.Property<int>("inquilino_id")
                        .HasColumnType("int")
                        .HasColumnName("inquilino_id");

                    b.Property<decimal>("montoAlquiler")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_alquiler");

                    b.HasKey("id");

                    b.HasIndex("inmueble_id");

                    b.HasIndex("inquilino_id");

                    b.ToTable("contratos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            estado = true,
                            fechaFinalizacion = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 1,
                            inquilino_id = 1,
                            montoAlquiler = 120000m
                        },
                        new
                        {
                            id = 2,
                            estado = true,
                            fechaFinalizacion = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 3,
                            inquilino_id = 2,
                            montoAlquiler = 95000m
                        },
                        new
                        {
                            id = 3,
                            estado = true,
                            fechaFinalizacion = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 4,
                            inquilino_id = 11,
                            montoAlquiler = 140000m
                        },
                        new
                        {
                            id = 4,
                            estado = true,
                            fechaFinalizacion = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 26,
                            inquilino_id = 12,
                            montoAlquiler = 99000m
                        },
                        new
                        {
                            id = 5,
                            estado = true,
                            fechaFinalizacion = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 27,
                            inquilino_id = 13,
                            montoAlquiler = 155000m
                        },
                        new
                        {
                            id = 6,
                            estado = true,
                            fechaFinalizacion = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 8,
                            inquilino_id = 14,
                            montoAlquiler = 78000m
                        },
                        new
                        {
                            id = 7,
                            estado = true,
                            fechaFinalizacion = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 19,
                            inquilino_id = 15,
                            montoAlquiler = 132000m
                        },
                        new
                        {
                            id = 8,
                            estado = false,
                            fechaFinalizacion = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 2,
                            inquilino_id = 3,
                            montoAlquiler = 55000m
                        },
                        new
                        {
                            id = 9,
                            estado = false,
                            fechaFinalizacion = new DateTime(2021, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 5,
                            inquilino_id = 4,
                            montoAlquiler = 68000m
                        },
                        new
                        {
                            id = 10,
                            estado = false,
                            fechaFinalizacion = new DateTime(2020, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2018, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 7,
                            inquilino_id = 5,
                            montoAlquiler = 63000m
                        },
                        new
                        {
                            id = 11,
                            estado = false,
                            fechaFinalizacion = new DateTime(2021, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 10,
                            inquilino_id = 6,
                            montoAlquiler = 80000m
                        },
                        new
                        {
                            id = 12,
                            estado = false,
                            fechaFinalizacion = new DateTime(2022, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 13,
                            inquilino_id = 7,
                            montoAlquiler = 90000m
                        },
                        new
                        {
                            id = 13,
                            estado = false,
                            fechaFinalizacion = new DateTime(2021, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2019, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 21,
                            inquilino_id = 8,
                            montoAlquiler = 78000m
                        },
                        new
                        {
                            id = 14,
                            estado = false,
                            fechaFinalizacion = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            fechaInicio = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            inmueble_id = 24,
                            inquilino_id = 9,
                            montoAlquiler = 95000m
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.ImagenInmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("inmueble_id")
                        .HasColumnType("int")
                        .HasColumnName("inmueble_id");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("url");

                    b.HasKey("id");

                    b.HasIndex("inmueble_id")
                        .IsUnique();

                    b.ToTable("imagenes_inmuebles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            inmueble_id = 1,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 2,
                            inmueble_id = 2,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 3,
                            inmueble_id = 3,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 4,
                            inmueble_id = 4,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 5,
                            inmueble_id = 5,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 6,
                            inmueble_id = 6,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 7,
                            inmueble_id = 7,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 8,
                            inmueble_id = 8,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 9,
                            inmueble_id = 9,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 10,
                            inmueble_id = 10,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 11,
                            inmueble_id = 11,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 12,
                            inmueble_id = 12,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 13,
                            inmueble_id = 13,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 14,
                            inmueble_id = 14,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 15,
                            inmueble_id = 15,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 16,
                            inmueble_id = 16,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 17,
                            inmueble_id = 17,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 18,
                            inmueble_id = 18,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 19,
                            inmueble_id = 19,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 20,
                            inmueble_id = 20,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 21,
                            inmueble_id = 21,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 22,
                            inmueble_id = 22,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 23,
                            inmueble_id = 23,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 24,
                            inmueble_id = 24,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 25,
                            inmueble_id = 25,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 26,
                            inmueble_id = 26,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        },
                        new
                        {
                            id = 27,
                            inmueble_id = 27,
                            url = "/uploads/inmuebles/test_casa.jpg"
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ambientes")
                        .HasColumnType("int")
                        .HasColumnName("ambientes");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("direccion");

                    b.Property<bool>("disponible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disponible");

                    b.Property<string>("latitud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("latitud");

                    b.Property<string>("longitud")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("longitud");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<int>("propietario_id")
                        .HasColumnType("int")
                        .HasColumnName("propietario_id");

                    b.Property<int>("superficie")
                        .HasColumnType("int")
                        .HasColumnName("superficie");

                    b.Property<int>("tipo_id")
                        .HasColumnType("int")
                        .HasColumnName("tipo_id");

                    b.Property<int>("uso_id")
                        .HasColumnType("int")
                        .HasColumnName("uso_id");

                    b.HasKey("id");

                    b.HasIndex("propietario_id");

                    b.HasIndex("tipo_id");

                    b.HasIndex("uso_id");

                    b.ToTable("inmuebles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            ambientes = 4,
                            direccion = "Av. España 102",
                            disponible = false,
                            latitud = "-33.296512",
                            longitud = "-66.335421",
                            precio = 120000m,
                            propietario_id = 1,
                            superficie = 140,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 2,
                            ambientes = 3,
                            direccion = "Belgrano 450",
                            disponible = true,
                            latitud = "-33.297845",
                            longitud = "-66.333210",
                            precio = 98000m,
                            propietario_id = 1,
                            superficie = 95,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 3,
                            ambientes = 2,
                            direccion = "Junín 780",
                            disponible = false,
                            latitud = "-33.298762",
                            longitud = "-66.331567",
                            precio = 75000m,
                            propietario_id = 1,
                            superficie = 70,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 4,
                            ambientes = 5,
                            direccion = "Mitre 1200",
                            disponible = false,
                            latitud = "-33.299843",
                            longitud = "-66.336789",
                            precio = 145000m,
                            propietario_id = 1,
                            superficie = 180,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 5,
                            ambientes = 3,
                            direccion = "Colón 350",
                            disponible = false,
                            latitud = "-33.301256",
                            longitud = "-66.334123",
                            precio = 210000m,
                            propietario_id = 1,
                            superficie = 110,
                            tipo_id = 3,
                            uso_id = 2
                        },
                        new
                        {
                            id = 6,
                            ambientes = 4,
                            direccion = "Buenos Aires 89",
                            disponible = true,
                            latitud = "-33.305612",
                            longitud = "-66.337456",
                            precio = 152000m,
                            propietario_id = 2,
                            superficie = 160,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 7,
                            ambientes = 3,
                            direccion = "Chacabuco 560",
                            disponible = true,
                            latitud = "-33.304123",
                            longitud = "-66.332345",
                            precio = 99000m,
                            propietario_id = 2,
                            superficie = 100,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 8,
                            ambientes = 2,
                            direccion = "San Martín 910",
                            disponible = false,
                            latitud = "-33.302981",
                            longitud = "-66.329876",
                            precio = 82000m,
                            propietario_id = 2,
                            superficie = 75,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 9,
                            ambientes = 5,
                            direccion = "Rivadavia 2100",
                            disponible = false,
                            latitud = "-33.306745",
                            longitud = "-66.340012",
                            precio = 165000m,
                            propietario_id = 2,
                            superficie = 200,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 10,
                            ambientes = 4,
                            direccion = "Pringles 45",
                            disponible = true,
                            latitud = "-33.303567",
                            longitud = "-66.327543",
                            precio = 230000m,
                            propietario_id = 2,
                            superficie = 150,
                            tipo_id = 3,
                            uso_id = 2
                        },
                        new
                        {
                            id = 11,
                            ambientes = 3,
                            direccion = "Pueyrredón 320",
                            disponible = true,
                            latitud = "-33.312345",
                            longitud = "-66.341234",
                            precio = 138000m,
                            propietario_id = 3,
                            superficie = 120,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 12,
                            ambientes = 2,
                            direccion = "Ituzaingó 654",
                            disponible = true,
                            latitud = "-33.310234",
                            longitud = "-66.338765",
                            precio = 87000m,
                            propietario_id = 3,
                            superficie = 68,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 13,
                            ambientes = 4,
                            direccion = "Catamarca 870",
                            disponible = false,
                            latitud = "-33.311789",
                            longitud = "-66.336543",
                            precio = 149000m,
                            propietario_id = 3,
                            superficie = 140,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 14,
                            ambientes = 1,
                            direccion = "Lafinur 120",
                            disponible = true,
                            latitud = "-33.309432",
                            longitud = "-66.333210",
                            precio = 110000m,
                            propietario_id = 3,
                            superficie = 55,
                            tipo_id = 4,
                            uso_id = 2
                        },
                        new
                        {
                            id = 15,
                            ambientes = 3,
                            direccion = "Ayacucho 410",
                            disponible = false,
                            latitud = "-33.308765",
                            longitud = "-66.331098",
                            precio = 96000m,
                            propietario_id = 3,
                            superficie = 105,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 16,
                            ambientes = 4,
                            direccion = "Independencia 1500",
                            disponible = true,
                            latitud = "-33.318765",
                            longitud = "-66.346543",
                            precio = 155000m,
                            propietario_id = 4,
                            superficie = 150,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 17,
                            ambientes = 3,
                            direccion = "Balcarce 620",
                            disponible = true,
                            latitud = "-33.316234",
                            longitud = "-66.342101",
                            precio = 93000m,
                            propietario_id = 4,
                            superficie = 98,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 18,
                            ambientes = 2,
                            direccion = "Los Puquios 45",
                            disponible = false,
                            latitud = "-33.320987",
                            longitud = "-66.347890",
                            precio = 78000m,
                            propietario_id = 4,
                            superficie = 65,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 19,
                            ambientes = 5,
                            direccion = "Illia 3450",
                            disponible = false,
                            latitud = "-33.317654",
                            longitud = "-66.349321",
                            precio = 172000m,
                            propietario_id = 4,
                            superficie = 210,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 20,
                            ambientes = 4,
                            direccion = "Ruta 3 Km 5",
                            disponible = true,
                            latitud = "-33.322345",
                            longitud = "-66.351234",
                            precio = 240000m,
                            propietario_id = 4,
                            superficie = 190,
                            tipo_id = 3,
                            uso_id = 2
                        },
                        new
                        {
                            id = 21,
                            ambientes = 3,
                            direccion = "Esteban Adaro 890",
                            disponible = true,
                            latitud = "-33.325678",
                            longitud = "-66.353456",
                            precio = 142000m,
                            propietario_id = 5,
                            superficie = 115,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 22,
                            ambientes = 2,
                            direccion = "Concarán 120",
                            disponible = true,
                            latitud = "-33.324321",
                            longitud = "-66.356789",
                            precio = 88000m,
                            propietario_id = 5,
                            superficie = 82,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 23,
                            ambientes = 1,
                            direccion = "Fraga 630",
                            disponible = false,
                            latitud = "-33.326543",
                            longitud = "-66.358901",
                            precio = 105000m,
                            propietario_id = 5,
                            superficie = 50,
                            tipo_id = 4,
                            uso_id = 2
                        },
                        new
                        {
                            id = 24,
                            ambientes = 4,
                            direccion = "El Trapiche 270",
                            disponible = false,
                            latitud = "-33.327890",
                            longitud = "-66.360123",
                            precio = 158000m,
                            propietario_id = 5,
                            superficie = 160,
                            tipo_id = 1,
                            uso_id = 1
                        },
                        new
                        {
                            id = 25,
                            ambientes = 3,
                            direccion = "Potrero de los Funes 410",
                            disponible = false,
                            latitud = "-33.329012",
                            longitud = "-66.362345",
                            precio = 215000m,
                            propietario_id = 5,
                            superficie = 130,
                            tipo_id = 3,
                            uso_id = 2
                        },
                        new
                        {
                            id = 26,
                            ambientes = 3,
                            direccion = "Riobamba 640",
                            disponible = false,
                            latitud = "-33.300432",
                            longitud = "-66.332654",
                            precio = 99000m,
                            propietario_id = 1,
                            superficie = 118,
                            tipo_id = 2,
                            uso_id = 1
                        },
                        new
                        {
                            id = 27,
                            ambientes = 5,
                            direccion = "España 520",
                            disponible = false,
                            latitud = "-33.302145",
                            longitud = "-66.334789",
                            precio = 168000m,
                            propietario_id = 1,
                            superficie = 175,
                            tipo_id = 1,
                            uso_id = 1
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inquilino", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("dni");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("id");

                    b.HasIndex("dni")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("inquilinos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            apellido = "Pérez",
                            dni = "30111222",
                            email = "juan.perez@example.com",
                            nombre = "Juan",
                            telefono = "2664100001"
                        },
                        new
                        {
                            id = 2,
                            apellido = "Giménez",
                            dni = "30999888",
                            email = "laura.gimenez@example.com",
                            nombre = "Laura",
                            telefono = "2664100002"
                        },
                        new
                        {
                            id = 3,
                            apellido = "Sosa",
                            dni = "32123456",
                            email = "martin.sosa@example.com",
                            nombre = "Martín",
                            telefono = "2664100003"
                        },
                        new
                        {
                            id = 4,
                            apellido = "Molina",
                            dni = "33987654",
                            email = "carolina.molina@example.com",
                            nombre = "Carolina",
                            telefono = "2664100004"
                        },
                        new
                        {
                            id = 5,
                            apellido = "Ríos",
                            dni = "34111222",
                            email = "pablo.rios@example.com",
                            nombre = "Pablo",
                            telefono = "2664100005"
                        },
                        new
                        {
                            id = 6,
                            apellido = "Silva",
                            dni = "35222333",
                            email = "jimena.silva@example.com",
                            nombre = "Jimena",
                            telefono = "2664100006"
                        },
                        new
                        {
                            id = 7,
                            apellido = "López",
                            dni = "36888999",
                            email = "ricardo.lopez@example.com",
                            nombre = "Ricardo",
                            telefono = "2664100007"
                        },
                        new
                        {
                            id = 8,
                            apellido = "Herrera",
                            dni = "37876543",
                            email = "sofia.herrera@example.com",
                            nombre = "Sofía",
                            telefono = "2664100008"
                        },
                        new
                        {
                            id = 9,
                            apellido = "Torres",
                            dni = "38901234",
                            email = "valeria.torres@example.com",
                            nombre = "Valeria",
                            telefono = "2664100009"
                        },
                        new
                        {
                            id = 10,
                            apellido = "Navarro",
                            dni = "39990123",
                            email = "diego.navarro@example.com",
                            nombre = "Diego",
                            telefono = "2664100010"
                        },
                        new
                        {
                            id = 11,
                            apellido = "Ponce",
                            dni = "40987654",
                            email = "marina.ponce@example.com",
                            nombre = "Marina",
                            telefono = "2664100011"
                        },
                        new
                        {
                            id = 12,
                            apellido = "Giuliani",
                            dni = "41223344",
                            email = "santiago.giuliani@example.com",
                            nombre = "Santiago",
                            telefono = "2664100012"
                        },
                        new
                        {
                            id = 13,
                            apellido = "Moreno",
                            dni = "42556677",
                            email = "celeste.moreno@example.com",
                            nombre = "Celeste",
                            telefono = "2664100013"
                        },
                        new
                        {
                            id = 14,
                            apellido = "Arias",
                            dni = "43667788",
                            email = "federico.arias@example.com",
                            nombre = "Federico",
                            telefono = "2664100014"
                        },
                        new
                        {
                            id = 15,
                            apellido = "Correa",
                            dni = "44778899",
                            email = "luciana.correa@example.com",
                            nombre = "Luciana",
                            telefono = "2664100015"
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("contrato_id")
                        .HasColumnType("int")
                        .HasColumnName("contrato_id");

                    b.Property<string>("detalle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("detalle");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("fechaPago")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("id");

                    b.HasIndex("contrato_id");

                    b.ToTable("pagos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            contrato_id = 1,
                            detalle = "Cuota enero 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 10000m
                        },
                        new
                        {
                            id = 2,
                            contrato_id = 1,
                            detalle = "Cuota febrero 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 10000m
                        },
                        new
                        {
                            id = 3,
                            contrato_id = 1,
                            detalle = "Cuota marzo 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 10000m
                        },
                        new
                        {
                            id = 4,
                            contrato_id = 1,
                            detalle = "Cuota abril 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 10000m
                        },
                        new
                        {
                            id = 5,
                            contrato_id = 1,
                            detalle = "Cuota mayo 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 10000m
                        },
                        new
                        {
                            id = 6,
                            contrato_id = 1,
                            detalle = "Cuota junio 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 10000m
                        },
                        new
                        {
                            id = 7,
                            contrato_id = 2,
                            detalle = "Cuota mayo 2023",
                            estado = true,
                            fechaPago = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9500m
                        },
                        new
                        {
                            id = 8,
                            contrato_id = 2,
                            detalle = "Cuota junio 2023",
                            estado = true,
                            fechaPago = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9500m
                        },
                        new
                        {
                            id = 9,
                            contrato_id = 2,
                            detalle = "Cuota julio 2023",
                            estado = true,
                            fechaPago = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9500m
                        },
                        new
                        {
                            id = 10,
                            contrato_id = 2,
                            detalle = "Cuota agosto 2023",
                            estado = true,
                            fechaPago = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9500m
                        },
                        new
                        {
                            id = 11,
                            contrato_id = 2,
                            detalle = "Cuota septiembre 2023",
                            estado = true,
                            fechaPago = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9500m
                        },
                        new
                        {
                            id = 12,
                            contrato_id = 3,
                            detalle = "Cuota julio 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 14000m
                        },
                        new
                        {
                            id = 13,
                            contrato_id = 3,
                            detalle = "Cuota agosto 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 14000m
                        },
                        new
                        {
                            id = 14,
                            contrato_id = 3,
                            detalle = "Cuota septiembre 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 14000m
                        },
                        new
                        {
                            id = 15,
                            contrato_id = 4,
                            detalle = "Cuota noviembre 2023",
                            estado = true,
                            fechaPago = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9900m
                        },
                        new
                        {
                            id = 16,
                            contrato_id = 4,
                            detalle = "Cuota diciembre 2023",
                            estado = true,
                            fechaPago = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9900m
                        },
                        new
                        {
                            id = 17,
                            contrato_id = 4,
                            detalle = "Cuota enero 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9900m
                        },
                        new
                        {
                            id = 18,
                            contrato_id = 4,
                            detalle = "Cuota febrero 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9900m
                        },
                        new
                        {
                            id = 19,
                            contrato_id = 4,
                            detalle = "Cuota marzo 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9900m
                        },
                        new
                        {
                            id = 20,
                            contrato_id = 4,
                            detalle = "Cuota abril 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9900m
                        },
                        new
                        {
                            id = 21,
                            contrato_id = 4,
                            detalle = "Cuota mayo 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9900m
                        },
                        new
                        {
                            id = 22,
                            contrato_id = 4,
                            detalle = "Cuota junio 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9900m
                        },
                        new
                        {
                            id = 23,
                            contrato_id = 5,
                            detalle = "Cuota febrero 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 15500m
                        },
                        new
                        {
                            id = 24,
                            contrato_id = 5,
                            detalle = "Cuota marzo 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 15500m
                        },
                        new
                        {
                            id = 25,
                            contrato_id = 5,
                            detalle = "Cuota abril 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 15500m
                        },
                        new
                        {
                            id = 26,
                            contrato_id = 5,
                            detalle = "Cuota mayo 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 15500m
                        },
                        new
                        {
                            id = 27,
                            contrato_id = 6,
                            detalle = "Cuota marzo 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 28,
                            contrato_id = 6,
                            detalle = "Cuota abril 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 29,
                            contrato_id = 6,
                            detalle = "Cuota mayo 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 30,
                            contrato_id = 6,
                            detalle = "Cuota junio 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 31,
                            contrato_id = 6,
                            detalle = "Cuota julio 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 32,
                            contrato_id = 7,
                            detalle = "Cuota mayo 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 13200m
                        },
                        new
                        {
                            id = 33,
                            contrato_id = 7,
                            detalle = "Cuota junio 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 13200m
                        },
                        new
                        {
                            id = 34,
                            contrato_id = 7,
                            detalle = "Cuota julio 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 13200m
                        },
                        new
                        {
                            id = 35,
                            contrato_id = 7,
                            detalle = "Cuota agosto 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 13200m
                        },
                        new
                        {
                            id = 36,
                            contrato_id = 7,
                            detalle = "Cuota septiembre 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 13200m
                        },
                        new
                        {
                            id = 37,
                            contrato_id = 7,
                            detalle = "Cuota octubre 2024",
                            estado = true,
                            fechaPago = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 13200m
                        },
                        new
                        {
                            id = 38,
                            contrato_id = 8,
                            detalle = "Cuota enero 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 5500m
                        },
                        new
                        {
                            id = 39,
                            contrato_id = 8,
                            detalle = "Cuota febrero 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 5500m
                        },
                        new
                        {
                            id = 40,
                            contrato_id = 8,
                            detalle = "Cuota marzo 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 5500m
                        },
                        new
                        {
                            id = 41,
                            contrato_id = 8,
                            detalle = "Cuota abril 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 5500m
                        },
                        new
                        {
                            id = 42,
                            contrato_id = 8,
                            detalle = "Cuota mayo 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 5500m
                        },
                        new
                        {
                            id = 43,
                            contrato_id = 8,
                            detalle = "Cuota junio 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 5500m
                        },
                        new
                        {
                            id = 44,
                            contrato_id = 8,
                            detalle = "Cuota julio 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 5500m
                        },
                        new
                        {
                            id = 45,
                            contrato_id = 8,
                            detalle = "Cuota agosto 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 5500m
                        },
                        new
                        {
                            id = 46,
                            contrato_id = 8,
                            detalle = "Cuota septiembre 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 5500m
                        },
                        new
                        {
                            id = 47,
                            contrato_id = 8,
                            detalle = "Cuota octubre 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 5500m
                        },
                        new
                        {
                            id = 48,
                            contrato_id = 9,
                            detalle = "Cuota junio 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6800m
                        },
                        new
                        {
                            id = 49,
                            contrato_id = 9,
                            detalle = "Cuota julio 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6800m
                        },
                        new
                        {
                            id = 50,
                            contrato_id = 9,
                            detalle = "Cuota agosto 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6800m
                        },
                        new
                        {
                            id = 51,
                            contrato_id = 9,
                            detalle = "Cuota septiembre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6800m
                        },
                        new
                        {
                            id = 52,
                            contrato_id = 9,
                            detalle = "Cuota octubre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6800m
                        },
                        new
                        {
                            id = 53,
                            contrato_id = 9,
                            detalle = "Cuota noviembre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6800m
                        },
                        new
                        {
                            id = 54,
                            contrato_id = 9,
                            detalle = "Cuota diciembre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6800m
                        },
                        new
                        {
                            id = 55,
                            contrato_id = 9,
                            detalle = "Cuota enero 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6800m
                        },
                        new
                        {
                            id = 56,
                            contrato_id = 9,
                            detalle = "Cuota febrero 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6800m
                        },
                        new
                        {
                            id = 57,
                            contrato_id = 10,
                            detalle = "Cuota marzo 2018",
                            estado = true,
                            fechaPago = new DateTime(2018, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6300m
                        },
                        new
                        {
                            id = 58,
                            contrato_id = 10,
                            detalle = "Cuota abril 2018",
                            estado = true,
                            fechaPago = new DateTime(2018, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6300m
                        },
                        new
                        {
                            id = 59,
                            contrato_id = 10,
                            detalle = "Cuota mayo 2018",
                            estado = true,
                            fechaPago = new DateTime(2018, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6300m
                        },
                        new
                        {
                            id = 60,
                            contrato_id = 10,
                            detalle = "Cuota junio 2018",
                            estado = true,
                            fechaPago = new DateTime(2018, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6300m
                        },
                        new
                        {
                            id = 61,
                            contrato_id = 10,
                            detalle = "Cuota julio 2018",
                            estado = true,
                            fechaPago = new DateTime(2018, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6300m
                        },
                        new
                        {
                            id = 62,
                            contrato_id = 10,
                            detalle = "Cuota agosto 2018",
                            estado = true,
                            fechaPago = new DateTime(2018, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6300m
                        },
                        new
                        {
                            id = 63,
                            contrato_id = 10,
                            detalle = "Cuota septiembre 2018",
                            estado = true,
                            fechaPago = new DateTime(2018, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 6300m
                        },
                        new
                        {
                            id = 64,
                            contrato_id = 11,
                            detalle = "Cuota septiembre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 8000m
                        },
                        new
                        {
                            id = 65,
                            contrato_id = 11,
                            detalle = "Cuota octubre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 8000m
                        },
                        new
                        {
                            id = 66,
                            contrato_id = 11,
                            detalle = "Cuota noviembre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 8000m
                        },
                        new
                        {
                            id = 67,
                            contrato_id = 11,
                            detalle = "Cuota diciembre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 8000m
                        },
                        new
                        {
                            id = 68,
                            contrato_id = 11,
                            detalle = "Cuota enero 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 8000m
                        },
                        new
                        {
                            id = 69,
                            contrato_id = 11,
                            detalle = "Cuota febrero 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 8000m
                        },
                        new
                        {
                            id = 70,
                            contrato_id = 12,
                            detalle = "Cuota abril 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9000m
                        },
                        new
                        {
                            id = 71,
                            contrato_id = 12,
                            detalle = "Cuota mayo 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9000m
                        },
                        new
                        {
                            id = 72,
                            contrato_id = 12,
                            detalle = "Cuota junio 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9000m
                        },
                        new
                        {
                            id = 73,
                            contrato_id = 12,
                            detalle = "Cuota julio 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9000m
                        },
                        new
                        {
                            id = 74,
                            contrato_id = 12,
                            detalle = "Cuota agosto 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9000m
                        },
                        new
                        {
                            id = 75,
                            contrato_id = 12,
                            detalle = "Cuota septiembre 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9000m
                        },
                        new
                        {
                            id = 76,
                            contrato_id = 12,
                            detalle = "Cuota octubre 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9000m
                        },
                        new
                        {
                            id = 77,
                            contrato_id = 12,
                            detalle = "Cuota noviembre 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9000m
                        },
                        new
                        {
                            id = 78,
                            contrato_id = 12,
                            detalle = "Cuota diciembre 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9000m
                        },
                        new
                        {
                            id = 79,
                            contrato_id = 12,
                            detalle = "Cuota enero 2021",
                            estado = true,
                            fechaPago = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9000m
                        },
                        new
                        {
                            id = 80,
                            contrato_id = 13,
                            detalle = "Cuota julio 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 81,
                            contrato_id = 13,
                            detalle = "Cuota agosto 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 82,
                            contrato_id = 13,
                            detalle = "Cuota septiembre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 83,
                            contrato_id = 13,
                            detalle = "Cuota octubre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 84,
                            contrato_id = 13,
                            detalle = "Cuota noviembre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 85,
                            contrato_id = 13,
                            detalle = "Cuota diciembre 2019",
                            estado = true,
                            fechaPago = new DateTime(2019, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 86,
                            contrato_id = 13,
                            detalle = "Cuota enero 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 87,
                            contrato_id = 13,
                            detalle = "Cuota febrero 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 7800m
                        },
                        new
                        {
                            id = 88,
                            contrato_id = 14,
                            detalle = "Cuota mayo 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9500m
                        },
                        new
                        {
                            id = 89,
                            contrato_id = 14,
                            detalle = "Cuota junio 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9500m
                        },
                        new
                        {
                            id = 90,
                            contrato_id = 14,
                            detalle = "Cuota julio 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9500m
                        },
                        new
                        {
                            id = 91,
                            contrato_id = 14,
                            detalle = "Cuota agosto 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9500m
                        },
                        new
                        {
                            id = 92,
                            contrato_id = 14,
                            detalle = "Cuota septiembre 2020",
                            estado = true,
                            fechaPago = new DateTime(2020, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 9500m
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Propietario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("dni");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("password");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("id");

                    b.HasIndex("dni")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("propietarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            activo = true,
                            apellido = "Gómez",
                            dni = "20123456",
                            email = "carlos.gomez@example.com",
                            nombre = "Carlos",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000001"
                        },
                        new
                        {
                            id = 2,
                            activo = true,
                            apellido = "Fernández",
                            dni = "20987654",
                            email = "maria.fernandez@example.com",
                            nombre = "María",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000002"
                        },
                        new
                        {
                            id = 3,
                            activo = true,
                            apellido = "Pérez",
                            dni = "19543210",
                            email = "lucia.perez@example.com",
                            nombre = "Lucía",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000003"
                        },
                        new
                        {
                            id = 4,
                            activo = true,
                            apellido = "Rodríguez",
                            dni = "21456789",
                            email = "javier.rodriguez@example.com",
                            nombre = "Javier",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000004"
                        },
                        new
                        {
                            id = 5,
                            activo = true,
                            apellido = "Lopez",
                            dni = "22345678",
                            email = "ana.lopez@example.com",
                            nombre = "Ana",
                            password = "7WJ3b3aActlm6nINXM8wAEI1UCovzqb3l6epF7wdZ+c=",
                            telefono = "2664000005"
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.TipoInmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("tipos_inmueble");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Casa"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Departamento"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Local Comercial"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Oficina"
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.UsoInmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("usos_inmueble");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Residencial"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Comercial"
                        });
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Inmueble", "Inmueble")
                        .WithMany("Contratos")
                        .HasForeignKey("inmueble_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InmobiliariaAPI.Domain.Entities.Inquilino", "Inquilino")
                        .WithMany("Contratos")
                        .HasForeignKey("inquilino_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.ImagenInmueble", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Inmueble", "Inmueble")
                        .WithOne("Imagen")
                        .HasForeignKey("InmobiliariaAPI.Domain.Entities.ImagenInmueble", "inmueble_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inmueble", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Propietario", "Propietario")
                        .WithMany("Inmuebles")
                        .HasForeignKey("propietario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InmobiliariaAPI.Domain.Entities.TipoInmueble", "Tipo")
                        .WithMany("Inmuebles")
                        .HasForeignKey("tipo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InmobiliariaAPI.Domain.Entities.UsoInmueble", "Uso")
                        .WithMany("Inmuebles")
                        .HasForeignKey("uso_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propietario");

                    b.Navigation("Tipo");

                    b.Navigation("Uso");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Pago", b =>
                {
                    b.HasOne("InmobiliariaAPI.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Pagos")
                        .HasForeignKey("contrato_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inmueble", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Inquilino", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.Propietario", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.TipoInmueble", b =>
                {
                    b.Navigation("Inmuebles");
                });

            modelBuilder.Entity("InmobiliariaAPI.Domain.Entities.UsoInmueble", b =>
                {
                    b.Navigation("Inmuebles");
                });
#pragma warning restore 612, 618
        }
    }
}
